name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v1

      - name: Set up virtual environment
        run: uv venv .venv

      - name: Install pre-commit
        run: uv pip install pre-commit

      - name: Run pre-commit checks
        run: .venv/bin/pre-commit run --all-files

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v1

      - name: Set up virtual environment
        run: uv venv .venv

      - name: Sync dependencies
        run: uv pip sync

      - name: Run tests
        run: .venv/bin/pytest --disable-warnings
