name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Install lint dependencies
        run: uv pip install . --group lint

      - name: Run Ruff
        run: ruff check .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Install dev dependencies
        run: uv pip install . --group dev

      - name: Run tests
        run: pytest

  pre-commit:
    name: Pre-commit validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Install pre-commit and hooks
        run: |
          uv pip install pre-commit
          pre-commit install-hooks

      - name: Run pre-commit on all files
        run: pre-commit run --all-files
